language: python
python:
  - 3.4
  - 3.6
dist: precise

services:
  - docker

matrix:
  fast_finish: true

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script: make lint/docker
      python: 3.6
      dist: trusty

install: make testdep
script: make test
